### ISSUE TITLE
Readme needs updating with current runbook

### ISSUE THREAD

**Issue by ptrelease** [hmcts/adoption-web#1482]
### What would you like to change?

Readme

### How do you think that would improve the project?

Will allow new devs to run the service locally

### If this entry is related to a bug, please provide the steps to reproduce it

These are the steps to run at the time of writing:

- Ensure the prerequisites from the Readme are met, then 
```shell
brew install redis
``` 
- Connect to F5 VPN
- Login to Azure
```shell 
az login --use-device-code
```
- Run a local version of Draft Store in a Docker container with a Redis image
```shell
docker-compose -f ./draft-store.yml up -d
```
- Go to this file: src/main/modules/draft-store/index.ts and comment out like this:
```
    const client = new Redis({
      host: config.get('services.draftStore.redis.host'),
      port: config.get('services.draftStore.redis.port'),
      /* password: config.get('session.redis.key'),
      tls: {
        servername: config.get('services.draftStore.redis.host'),
      }, */
    });

```

(You can start this from Docker Desktop thereafter)

- install dependencies
```shell
yarn install
```

- Bundle
```shell
yarn webpack
```

- Run, and access on localhost:3001
```shell
yarn start:dev
```

**Comment by hfilmore** [comment]
Troubleshooting:
Installing dependencies can hit issues where a later version of node is used, e.g. v21.5.0
Solution: use Node Version Manager to change to a supported version:
`nvm use 18.15.0`

**Comment by hfilmore** [comment]
Work underway: https://github.com/hmcts/adoption-web/pull/1492

**Comment by hfilmore** [comment]
Done as part of PR 1492
