### ISSUE TITLE
Hardcoded fee values on eligibility start page

### ISSUE THREAD

**Issue by ptrelease** [hmcts/adoption-web#1483]
### What would you like to change?

EligibilityStartGetController called the fee API.  This is unnecessary now.

### Work below is no longer an issue 
(- as the fee content has been removed from the eligibility start page)

/eligibility/start correctly uses the fee service to get the fee value for line 9 of the page.

However, line 12 of the page has a hardcoded fee value of £183.

In addition, line 9 and line 12 for the Welsh version of this page is hardcoded to £183.

### How do you think that would improve the project?

If the fee changes, the the eligibility pages would be wrong for en and cy users.

#### Change start/content.ts so that the en line 12 is:

```
line12:
    `If you're applying for more than one child, you must submit a new application for each child. You will not be charged if you submit these before midnight on the day of your first application. If you submit after the day of the first application, you will be charged another £${content.fee?.FeeAmount}. For this reason we recommend you begin the applications early and have everything you need.`,
```

#### Change start/content.ts so that content is passed when creating the cy const:
```
const cy: typeof en = content => ({
```

#### Change start/content.ts so that Welsh versions of the content get the fee value dynamically
```
line9:
    `Ffi prosesu’r llys ar gyfer gwneud cais yw £${content.fee?.FeeAmount}. Mae’r taliad yn ddyledus unwaith y bydd y cais wedi’i gwblhau ac yn barod i’w gyflwyno i’r llys.`,

line12:
    `Os ydych chi’n gwneud cais i fabwysiadu mwy nag un plentyn, mae’n rhaid i chi gyflwyno cais newydd ar gyfer pob plentyn. Ni chodir ffi arall arnoch os byddwch yn cyflwyno’r ceisiadau hyn cyn hanner nos ar ddyddiad cyflwyno’ch cais cyntaf. Os byddwch yn eu cyflwyno ar ôl dyddiad cyflwyno’r cais cyntaf, yna bydd rhaid i chi dalu £${content.fee?.FeeAmount} arall. Am y rheswm hwn, argymhellwn eich bod yn dechrau eich ceisiadau yn gynnar a bod gennych bopeth rydych ei angen wrth law.`,
```

**Comment by hfilmore** [comment]
No longer required as removed.
